Repository COSC481W-2022Winter/capstone-wicrosoft, pull requests merged in 2022-04, with the labels that each got.

#39 Feat: add Skill Acceptance to main
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  templates/skill_acceptance.html
Labels: Priority: Medium, Additions: Feature, Sprint: Three

#40 feat: Search Utility
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  static/css/page_titles.css
  static/css/search.css
  static/css/utilities/spinner.boot.css
  static/images/components/search-grey.svg
  static/images/components/search.svg
  static/js/search/search.js
  templates/nav.html
  templates/search.html
Labels: Priority: Medium, Additions: Feature, Pending: Waiting On Review, Sprint: Three

#41 feat: Managers Can Edit Team
  djangoresourcemanagement/views.py
  static/css/profile.css
  static/js/teams/teamview.js
  templates/profile.html
Labels: Priority: Medium, Pending: Waiting On Review, Sprint: Three

#42 feat: Managers Can Edit Projects
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  static/css/edit_frm.css
  static/js/projectmaker/edit_projectmaker.js
  templates/edit_project.html
  templates/profile.html
Labels: Priority: Medium, RESOLVED, Sprint: Three

#52 #43 Ola austin kelly add skill reason
  djangoresourcemanagement/views.py
  static/js/addskills/skills_addskills.js
  templates/skills.html
Labels: Priority: Medium, Additions: Feature, Sprint: Four

#54 fix:Search filters do automatic search
  static/js/search/search.js
Labels: RESOLVED

#56 feat: Directory Page - Issue #48
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  static/css/directory.css
  templates/directory.html
  templates/nav.html
  templates/search.html
Labels: Priority: Medium, Additions: Feature, Pending: Waiting On Review, Sprint: Four

#59 Fix: project owner link
  templates/project_display.html
Labels: Improvements: Enhancement
