Repository COSC481W-2022Winter/capstone-wicrosoft, pull requests merged in 2022-02, with the labels that each got.

#7 fix: Typo in readme corrected
  README.md
Labels: Mindless: Documentation

#8 Feat: Log in capabilities
  djangoresourcemanagement/views.py
  templates/login.html
Labels: Priority: Low, Additions: Feature, Sprint: One, Pending: Waiting On Review

#10 Team Creatin Form Works and Satisfies PBI
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/models.py
  djangoresourcemanagement/views.py
  static/css/teamForm.css
  static/css/utilities/autocomplete.css
  static/js/teammaker/teammaker_autocomplete.js
  static/js/utilities/jquery.autocomplete.js
  templates/team_maker.html
Labels: Additions: Feature, Sprint: One, Pending: Waiting On Review

#9 Feat: login and profile page capabilities
  djangoresourcemanagement/views.py
  static/css/profile.css
  static/css/user_credentials/login.css
  templates/login.html
  templates/profile.html
Labels: Priority: Low, Additions: Feature, Sprint: One, Pending: Waiting On Review
