Repository COSC481W-2022Winter/capstone-wicrosoft, pull requests merged in 2022-03, with the labels that each got.

#13 #12 Kelly jacob update refactor import users
  djangoresourcemanagement/HelperFunctions.py
  djangoresourcemanagement/views.py
  templates/importusers.html
Labels: Priority: Medium

#19 Requesting Review of Navigation For Merge To Main
  static/images/components/box-arrow-in-right.svg
  static/images/components/box-arrow-left.svg
  static/images/logo/wicrosoft_logo.svg
  templates/importusers.html
  templates/nav.html
  templates/profile.html
  templates/team_maker.html
Labels: Additions: Feature, Sprint: Two

#20 #15 Faizan lieske elwell create skill page
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  requirements.txt
  static/css/skills.css
  static/js/addskills/skills_addskills.js
  templates/skills.html
Labels: Priority: High, Additions: Feature, RESOLVED, Sprint: Two

#23 feat: allows users to add skills to their account
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  static/css/skills.css
  static/js/addskills/skills_addskills.js
  templates/skills.html
Labels: Priority: Medium, RESOLVED, Sprint: Two

#25 Bug: Duplication of Teams
  djangoresourcemanagement/views.py
Labels: Priority: Medium, Problem: Bug, Pending: Waiting On Review

#37 Elijah jacob ola user display
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  static/css/user_display.css
  templates/user_display.html
Labels: Priority: High, Pending: Waiting On Review, Sprint: Three

#36 Elijah jacob ola team display
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  templates/display_team.html
Labels: Priority: High, Pending: Waiting On Review, Sprint: Three

#35 Elijah jacob ola project display
  capstone_wicrosoft/urls.py
  djangoresourcemanagement/views.py
  templates/project_display.html
Labels: Priority: High, Pending: Waiting On Review, Sprint: Three
